### ISSUE TITLE
Multi-issue

### ISSUE THREAD

**Issue by LinusOstlund** [repobee/repobee-feedback#11]
I'm  trying to use the multi-issue function. 

I would love to  see an explicit example, as I'm not really sure how to use this. 
The "see optional arguments"-link seems dead.

**Comment by LinusOstlund** [comment]
Okay so I had forgotten to activate the plugin (...) so the `-h`-didnt work. 
The command that worked was, where `--mi` means _multiple issues_ and all issues are in the `feedback-3.md` file:
```
repobee issues feedback -a task-3 --sf students.txt --mi feedback-3.md
```
I'll leave this open since the "see optional arguments" still is dead.

**Comment by slarse** [comment]
Would you like something like this at the end of the `Using the feedback command` section:

If you are using the multi issues file, then you must also add the `--mi|--multi-issues-file` option with a path to the file.

```
$ repobee repobee issues feedback -a task-1 -s slarse rjglasse --mi path/to/issues.md
```

**Comment by slarse** [comment]
Closing as stale.
