### ISSUE TITLE
Auto generate multi-issue file

### ISSUE THREAD

**Issue by tohanss** [repobee/repobee-feedback#12]
I'm getting real tired of adding 

#ISSUE#name-task-X#Pass/fail

to a file 15 times so I considered writing a plugin to do that for me but realized I can just add it to the feedback plugin if that's okay with you @slarse 

I'm thinking something like:

`repobee issues feedback create-mi-file`

**Comment by slarse** [comment]
Sure, seems like it would be an easy enough thing to add. You should be able to easily create the command with a couple of base parsers, probably [BaseParser.STUDENTS](https://repobee.readthedocs.io/en/latest/repobee_plug/code.html?highlight=BaseParser#repobee_plug.cli.base.BaseParser.STUDENTS) and [BaseParser.ASSIGMENTS](https://repobee.readthedocs.io/en/latest/repobee_plug/code.html?highlight=BaseParser#repobee_plug.cli.base.BaseParser.ASSIGNMENTS).

Shouldn't need any more options, just `--assignments` and `--students` should be fine.

**Comment by marceloFA** [comment]
Can I work on this? :)

**Comment by slarse** [comment]
@marceloFA Yes, go ahead :)

**Comment by slarse** [comment]
The command should probably be something like `repobee issues generate-multi-issue-file`. You can probably figure out how to do that by just looking at the other command in the `feedback` module, but if you need more info the docs are here: https://docs.repobee.org/en/stable/repobee_plug/creating_plugins.html#commands
